-- AM-45: Granthalaya deity rows for bundled Aangan art that had no catalog entry.
-- Idempotent. Applied live via execute_sql; keep in repo for local replay.

INSERT INTO deities (
  slug, name, name_sanskrit, title_hindi, image_url, description, mythology,
  iconography, family, mantras, sacred_number, sacred_day, festivals,
  how_to_worship, temples, color, timeline, order_index, is_active
) VALUES
(
  'vishnu',
  'Vishnu',
  'विष्णु',
  'विष्णु',
  NULL,
  'The preserver of the Trimurti, who descends as avatars whenever dharma declines.',
  'Lord Vishnu, the Narayana, sustains the universe while reclining on the serpent Shesha in the causal ocean, Lakshmi at his feet. When adharma rises, he takes birth as an avatar — Matsya, Kurma, Varaha, Narasimha, Vamana, Parashurama, Rama, Krishna, and others — to restore balance. He is the inner witness (Antaryami) and the friend of devotees. The Gita is spoken by his Krishna form; the Ramayana follows his Rama form. Vaishnavas worship him as the supreme person, yet he is also one face of the Trimurti alongside Brahma and Shiva.',
  '{"forms":["Narayana","Venkateswara","Ranganatha","Jagannath","Hayagriva"],"mount":"Garuda","symbols":["Shankha (conch)","Sudarshana Chakra","Padma (lotus)","Kaustubha gem","Vanamala"],"weapons":["Sudarshana Chakra","Kaumodaki (mace)","Nandaka (sword)","Saranga (bow)"]}'::jsonb,
  '{"consort":"Lakshmi","parents":"Sage Kashyapa and Aditi (as Upendra); otherwise self-existent Narayana","children":["Kamadeva","Devasena (in some traditions)"],"avatars":["Rama","Krishna","Narasimha"]}'::jsonb,
  ARRAY['ॐ नमो भगवते वासुदेवाय (Om Namo Bhagavate Vasudevaya)','ॐ नमो नारायणाय (Om Namo Narayanaya)','हरे कृष्ण हरे राम'],
  108,
  'Thursday',
  '[{"name":"Vaikuntha Ekadashi","month":"December/January","description":"The gates of Vaikuntha are said to open; devotees fast and keep vigil."},{"name":"Rama Navami","month":"March/April","description":"The appearance day of Rama, Vishnu''s maryada avatar."},{"name":"Janmashtami","month":"August/September","description":"The appearance day of Krishna, Vishnu''s leela avatar."}]'::jsonb,
  E'1. Bathe and wear clean, preferably yellow or pitambara-colored cloth\n2. Sit before a Vishnu or saligrama form, or a picture of Narayana\n3. Offer tulsi leaves — Vishnu''s dearest offering\n4. Light a ghee diya and incense\n5. Chant "Om Namo Narayanaya" or the Vishnu Sahasranama\n6. Offer water, fruit, and sweets (especially kheer or payasam)\n7. Read a few verses of the Gita or a Rama/Krishna story\n8. Observe Thursday (Guruvar) or Ekadashi vrata when you can\n9. End with aarti and a simple prostration',
  '[{"name":"Tirumala Venkateswara","city":"Tirupati, AP"},{"name":"Badrinath","city":"Uttarakhand"},{"name":"Sri Ranganathaswamy","city":"Srirangam, TN"},{"name":"Jagannath","city":"Puri, Odisha"},{"name":"Padmanabhaswamy","city":"Thiruvananthapuram, KL"}]'::jsonb,
  '#0284C7',
  '[{"era":"Before Creation","title":"Narayana on Shesha","description":"Vishnu rests on the infinite serpent in the causal ocean; a lotus rises from his navel and Brahma begins creation."},{"era":"Satya Yuga","title":"Varaha and Narasimha","description":"He lifts the earth as the boar Varaha and protects Prahlada as the man-lion Narasimha."},{"era":"Treta Yuga","title":"Rama of Ayodhya","description":"As Rama he lives the dharma of a son, husband, and king; the Ramayana records that path."},{"era":"Dvapara Yuga","title":"Krishna of Vrindavan and Kurukshetra","description":"As Krishna he reveals the Gita to Arjuna and draws devotees through leela and counsel."},{"era":"Eternal","title":"The inner witness","description":"Vaishnava teaching holds that Vishnu dwells in the heart as Antaryami, the companion of every jiva."}]'::jsonb,
  9,
  true
),
(
  'narasimha',
  'Narasimha',
  'नरसिंह',
  'नरसिंह',
  NULL,
  'Vishnu''s fierce man-lion avatar, who appears to protect a child''s bhakti and destroy tyranny.',
  'Hiranyakashipu won a boon that he could not be killed by man or beast, indoors or outdoors, by day or night, on earth or in the sky, by any weapon. His son Prahlada would not stop chanting Vishnu''s name. In rage the king struck a pillar in the palace courtyard at twilight. The pillar split, and Narasimha — neither man nor animal — emerged. He placed the king on his lap on the threshold and tore him with claws, fulfilling the boon and the prayer at once. After the slaying, the fierce form was cooled by Prahlada''s devotion and by Lakshmi. Narasimha is worshipped as the protector of devotees and the destroyer of inner asuras — pride, cruelty, and fear.',
  '{"forms":["Ugra Narasimha","Lakshmi Narasimha","Yoga Narasimha","Ahobilam Nava Narasimha"],"mount":"None (seated on the threshold / lion seat)","symbols":["Lion mane","Pillar","Claws","Prahlada at his feet"],"weapons":["Claws (nakha)","Sudarshana in some forms"]}'::jsonb,
  '{"consort":"Lakshmi (as Lakshmi Narasimha)","parents":"Avatar of Vishnu","children":[],"related":["Prahlada"]}'::jsonb,
  ARRAY['ॐ नृसिंहाय नमः (Om Nrisimhaya Namah)','उग्रं वीरं महाविष्णुं — नृसिंह तापनीय','ॐ क्ष्रौं नृसिंहाय नमः'],
  32,
  'Saturday',
  '[{"name":"Narasimha Jayanti","month":"April/May","description":"The appearance day of Narasimha, observed with fasting and recitation of the Narasimha stotra."},{"name":"Vaikuntha Ekadashi","month":"December/January","description":"Vaishnava vigil; many temples include Narasimha in the darshan cycle."}]'::jsonb,
  E'1. Approach with humility — this is a ugra (fierce) form cooled by bhakti\n2. Offer red flowers, jaggery, and panakam where that is the temple custom\n3. Light a lamp and incense before the image or yantra\n4. Chant "Om Nrisimhaya Namah" or the Narasimha Kavacham\n5. Remember Prahlada — courage and softness together\n6. Saturday worship is traditional in many South Indian homes\n7. End with aarti; do not treat the fierce form as a weapon against others',
  '[{"name":"Ahobilam","city":"Andhra Pradesh"},{"name":"Yadagirigutta","city":"Telangana"},{"name":"Simhachalam","city":"Visakhapatnam, AP"},{"name":"Melkote Yoga Narasimha","city":"Karnataka"},{"name":"Shri Lakshmi Narasimha, Mangalagiri","city":"Andhra Pradesh"}]'::jsonb,
  '#B45309',
  '[{"era":"Satya Yuga","title":"The boon and the pillar","description":"Hiranyakashipu''s boon seemed airtight until Vishnu chose a form and a moment the words could not cover."},{"era":"Satya Yuga","title":"Prahlada''s faith","description":"A child''s nama-smarana called the Lord out of stone; devotion, not force, opened the avatar."},{"era":"Satya Yuga","title":"The cooling","description":"Lakshmi and Prahlada soothe Ugra Narasimha so the world is not burned by leftover wrath."},{"era":"Eternal","title":"Protector of the devoted","description":"Temples from Ahobilam to Simhachalam keep Narasimha as the guardian who stands at the threshold."}]'::jsonb,
  10,
  true
),
(
  'kartikeya',
  'Kartikeya',
  'कार्तिकेय',
  'कार्तिकेय',
  NULL,
  'Son of Shiva and Parvati; commander of the gods'' army, worshipped as Murugan, Skanda, and Subrahmanya.',
  'Kartikeya was born to defeat the asura Taraka, whose boon said only a son of Shiva could slay him. The spark of Shiva''s tejas was carried by Agni and Ganga and nurtured by the six Krittikas — hence the name Kartikeya and the six faces of Shanmukha. He received the vel (spear) from Parvati, took command of the Deva senas, and killed Taraka. In Tamil country he is Murugan, the beloved hill-god of youth, poetry, and victory; his consorts are Valli and Devasena. He is the brother of Ganesha; stories of the mango and of circling the world teach that wisdom and valor are both paths to the parents'' blessing.',
  '{"forms":["Shanmukha","Murugan","Skanda","Subrahmanya","Kumara"],"mount":"Peacock (Paravani)","symbols":["Vel (spear)","Rooster banner","Six faces","Peacock feather"],"weapons":["Vel","Bow in some forms"]}'::jsonb,
  '{"consort":"Valli and Devasena","parents":"Shiva and Parvati","siblings":["Ganesha"],"foster":"The six Krittikas"}'::jsonb,
  ARRAY['ॐ सरवणभवाय नमः (Om Saravanabhavaya Namah)','वेलुக்கு வெற்றி — Muruga vel','ॐ स्कन्दाय नमः'],
  6,
  'Tuesday',
  '[{"name":"Skanda Shashti","month":"October/November","description":"Six-day vrata recalling the war with Taraka / Soorapadman; culminates in soorasamharam."},{"name":"Thaipusam","month":"January/February","description":"Devotees carry kavadi for Murugan, especially in Tamil and diaspora temples."},{"name":"Vaikasi Visakam","month":"May/June","description":"Appearance festival of Murugan in the Tamil calendar."}]'::jsonb,
  E'1. Offer red or yellow flowers and a small spear or vel if you keep one at home\n2. Light camphor or a ghee lamp\n3. Chant "Om Saravanabhavaya Namah" six times or in malas of 108\n4. Tuesday and Shashti thithi are especially dear to him\n5. Read a short Murugan or Skanda story with children when you can\n6. Offer fruit — bananas and pomegranates are common\n7. End with aarti and a wish that courage stay kind',
  '[{"name":"Palani Murugan","city":"Tamil Nadu"},{"name":"Tiruchendur","city":"Tamil Nadu"},{"name":"Swamimalai","city":"Tamil Nadu"},{"name":"Tiruttani","city":"Tamil Nadu"},{"name":"Pazhamudircholai","city":"Tamil Nadu"}]'::jsonb,
  '#7C3AED',
  '[{"era":"Satya Yuga","title":"Birth for Taraka","description":"The gods pray for a commander; Shiva''s tejas becomes the child who can end Taraka''s boon."},{"era":"Satya Yuga","title":"Six mothers, six faces","description":"The Krittikas nurse him; Shanmukha holds six kinds of knowing in one glance."},{"era":"Satya Yuga","title":"The vel and the war","description":"Parvati gives the vel; Kartikeya leads the Devas and slays Taraka."},{"era":"Eternal","title":"Murugan of the hills","description":"The six abodes (Arupadai Veedu) in Tamil Nadu remain living centers of youth, poetry, and vow."}]'::jsonb,
  11,
  true
),
(
  'indra',
  'Indra',
  'इन्द्र',
  'इन्द्र',
  NULL,
  'King of the Devas and lord of rain and thunder; a Vedic sovereign whose pride the Puranas also humble.',
  'In the Rig Veda, Indra is the foremost of the gods — wielder of the vajra, drinker of soma, slayer of Vritra who had imprisoned the waters. He releases rivers and light for the world. In later Puranic tellings he remains king of Svarga, but stories of his pride — the theft of the Parijata, the insult to Durvasa, the hiding from Krishna at Govardhana — show that even the king of heaven must bow to a higher dharma. He rides the white elephant Airavata. Farmers and kings once invoked him for rain and victory. In Antar Marg he is remembered as the Vedic face of courage, and as a reminder that power without humility dries up.',
  '{"forms":["Vajrapani Indra","Sakra (Buddhist/Jain telling)","Devendra"],"mount":"Airavata (white elephant)","symbols":["Vajra (thunderbolt)","Rainbow","Rain cloud","Soma cup"],"weapons":["Vajra"]}'::jsonb,
  '{"consort":"Shachi (Indrani)","parents":"Kashyapa and Aditi","children":["Jayanta","Jayanti"],"realm":"Svarga / Amaravati"}'::jsonb,
  ARRAY['ॐ इन्द्राय नमः (Om Indraya Namah)','इन्द्रं वो विश्वतस्परि — Rigvedic invocation','ॐ वज्रहस्ताय नमः'],
  1000,
  'Sunday',
  '[{"name":"Indra Jatra","month":"September (Nepal)","description":"Kathmandu''s festival of Indra and the lowering of the lingo pole."},{"name":"Govardhan Puja","month":"October/November","description":"Krishna lifts Govardhana; the story humbles Indra''s rain-pride and teaches shelter in the Lord."}]'::jsonb,
  E'1. Remember Indra as rain and courage, not as a rival to the ishta-devata you already love\n2. A simple water offering and a lamp are enough at home\n3. On days of needed rain or before a hard effort, chant "Om Indraya Namah"\n4. Read one Rigvedic hymn or the Govardhana story so pride stays in view\n5. Offer white flowers if you keep a small image\n6. End with gratitude for water, sky, and the chance to begin again',
  '[{"name":"Indreshwar","city":"Khajuraho / several regional shrines"},{"name":"Indra temple traditions","city":"Kathmandu (Indra Jatra)"},{"name":"Vedic recitation halls","city":"Across India — Indra lives primarily in mantra, not one all-India mandir"}]'::jsonb,
  '#CA8A04',
  '[{"era":"Vedic","title":"Slayer of Vritra","description":"Indra shatters the serpent who hoarded the waters; rivers and dawn move again."},{"era":"Vedic","title":"King of Svarga","description":"He rules Amaravati with Shachi; the vajra is both weapon and royal emblem."},{"era":"Dvapara Yuga","title":"Govardhana","description":"Krishna teaches the cowherds to honor the mountain and the earth; Indra''s storm meets a lifted hill."},{"era":"Puranic","title":"The lesson of pride","description":"Again and again Indra is corrected — so that kingship stays a seva, not a throne for the ego."}]'::jsonb,
  12,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  name_sanskrit = EXCLUDED.name_sanskrit,
  title_hindi = EXCLUDED.title_hindi,
  description = EXCLUDED.description,
  mythology = EXCLUDED.mythology,
  iconography = EXCLUDED.iconography,
  family = EXCLUDED.family,
  mantras = EXCLUDED.mantras,
  sacred_number = EXCLUDED.sacred_number,
  sacred_day = EXCLUDED.sacred_day,
  festivals = EXCLUDED.festivals,
  how_to_worship = EXCLUDED.how_to_worship,
  temples = EXCLUDED.temples,
  color = EXCLUDED.color,
  timeline = EXCLUDED.timeline,
  order_index = EXCLUDED.order_index,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
